# Testing exception warning
from warnings import warn, showwarning
a = 1
b=2

warn("sup")
print((a + b))